resources:
  pipelines:
    pipeline:
      name: pipeline
      libraries:
        - glob:
            include: ../../src/pipeline/transformations/**
      serverless: true
      catalog: ${var.env}_bronze
      schema: ${workspace.current_user.short_name}
      root_path: ../../src/pipeline/