resources:
  pipelines:
    pipeline:
      name: pipeline
      libraries:
        - glob:
            include: ../../src/pipeline/transformations/**
      serverless: true
      catalog: ${var.env}_bronze
      schema: ${workspace.current_user.short_name}
<<<<<<< HEAD
      root_path: ../src/pipeline
      configuration:
        catalog_name: ${var.env}_bronze
        schema_name: ${workspace.current_user.short_name}
        volume_name: ${resources.volumes.landing.name}
=======
      root_path: ../../src/pipeline/
>>>>>>> 6c8f2f16badda9287d1d757fff0ef0ce1ddad7d9
