resources:
  pipelines:
    pipeline:
      name: pipeline
      libraries:
        - glob:
            include: ../../src/pipeline/transformations/**
      serverless: true
      catalog: ${var.env}_bronze
      schema: dev_tyler_tracey_cities
      root_path: ../src/pipeline
      configuration:
        catalog_name: ${var.env}_bronze
        schema_name: dev_tyler_tracey_cities
        volume_name: ${resources.volumes.landing.name}
